# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github
        
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/aegean-next/aegean-next-origin" }]'
        servers: '[{ "id": "github", "username": "rainyblossom", "password": "${{ github.token }}" }]'
          
    - name: Import GPG Config
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PRIVATE_PASSPHRASE }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
